# Generated by Django 5.1.5 on 2025-01-31 10:29

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChickenOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField()),
                ('invoice_no', models.CharField(default=inventory.models.generate_unique_invoice_no, max_length=50, unique=True)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='uploads/chicken_orders/')),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10)),
                ('payment_mode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('check', 'Check')], max_length=10, null=True)),
                ('check_no', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver_name', models.CharField(max_length=255)),
                ('storage_location', models.CharField(choices=[('stock_room', 'Stock Room'), ('cold_storage', 'Cold Storage')], default='stock_room', max_length=20)),
                ('total_amount', models.FloatField(default=0.0)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vendor')),
            ],
        ),
    ]
